name: Build & Test

on:
  push:
    branches: [main]
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-key-suffix: ${{ hashFiles('uv.lock') }}

      - name: Verify uv version
        run: uv --version

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff format check
        run: uv run ruff format --check .

      - name: Run Ruff lint check
        run: uv run ruff check .

      - name: Run isort lint check
        run: uv run isort . --check

      - name: Run Mypy type check
        run: uv run mypy .

      - name: Run unit tests
        run: uv run pytest

      - name: Build distribution
        run: mkdir dist && uv build -o dist

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: dist
          path: dist/*
          overwrite: true

  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-and-test
    uses: ./.github/workflows/release.yml
